/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Simulation_of_Inventory_Systems;

import java.awt.Color;
import java.io.FileOutputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.application.Application;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.apache.poi.sl.usermodel.ObjectMetaData;
import org.apache.poi.sl.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author ATD
 */
public class FRM_investory extends javax.swing.JFrame {

    /**
     * Creates new form FRM_investory
     */
    public FRM_investory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Table_Total = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        Table_N_Distrib_with_R_To_Type = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jbtn_Calc_table_Newsday_Distribution = new javax.swing.JButton();
        jbtn_Get_Last_Table = new javax.swing.JButton();
        btn_putValue_Step1 = new javax.swing.JButton();
        jbtn_Calc_Step2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn_Draw = new javax.swing.JButton();
        btn_Get_Excel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_putValue_From_Yourself = new javax.swing.JButton();
        btnTrueFalse = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Table_NewsdayWithRandomDigit_Type = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table_Newsday_Distribution = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_New_Type = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Limits = new javax.swing.JTable();
        btn_Show_info = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(53, 215, 29));

        jScrollPane6.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N

        Table_Total.setBackground(new java.awt.Color(255, 4, 108));
        Table_Total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Table_Total.setForeground(new java.awt.Color(51, 0, 0));
        Table_Total.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Day", "R.D.For type of Newday", "Type of New day", "R.D for demand", "Demand", "Revenue from Sale", "Lost profit from Excess Demand", "Salvage from Scrap Sale", "Daily profit", "#of remaining newspapers", "Net profit", "True Lost", "Full True Lost"
            }
        ));
        Table_Total.setIntercellSpacing(new java.awt.Dimension(3, 3));
        Table_Total.setMinimumSize(new java.awt.Dimension(65, 222));
        jScrollPane6.setViewportView(Table_Total);

        jScrollPane5.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N

        Table_N_Distrib_with_R_To_Type.setBackground(new java.awt.Color(96, 162, 41));
        Table_N_Distrib_with_R_To_Type.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Table_N_Distrib_with_R_To_Type.setForeground(new java.awt.Color(102, 0, 0));
        Table_N_Distrib_with_R_To_Type.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Demand", "Prob_Good", "Prob_Fair", "Prob_Poor", "Cumulative_Good", "Cumulative_Fair", "Cumulative_Poor", "From_Good", "To_Good", "From_Fair", "To_Fair", "From_Poor", "To_Poor"
            }
        ));
        Table_N_Distrib_with_R_To_Type.setIntercellSpacing(new java.awt.Dimension(3, 3));
        Table_N_Distrib_with_R_To_Type.setMinimumSize(new java.awt.Dimension(65, 222));
        jScrollPane5.setViewportView(Table_N_Distrib_with_R_To_Type);

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));

        jbtn_Calc_table_Newsday_Distribution.setBackground(new java.awt.Color(204, 0, 0));
        jbtn_Calc_table_Newsday_Distribution.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn_Calc_table_Newsday_Distribution.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Calc_table_Newsday_Distribution.setText("Step 3");
        jbtn_Calc_table_Newsday_Distribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_Calc_table_Newsday_DistributionActionPerformed(evt);
            }
        });

        jbtn_Get_Last_Table.setBackground(new java.awt.Color(204, 0, 0));
        jbtn_Get_Last_Table.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn_Get_Last_Table.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Get_Last_Table.setText("ok");
        jbtn_Get_Last_Table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_Get_Last_TableActionPerformed(evt);
            }
        });

        btn_putValue_Step1.setBackground(new java.awt.Color(204, 0, 0));
        btn_putValue_Step1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_putValue_Step1.setForeground(new java.awt.Color(255, 255, 255));
        btn_putValue_Step1.setText("Step 1");
        btn_putValue_Step1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_putValue_Step1ActionPerformed(evt);
            }
        });

        jbtn_Calc_Step2.setBackground(new java.awt.Color(204, 0, 0));
        jbtn_Calc_Step2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn_Calc_Step2.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Calc_Step2.setText("Step 2");
        jbtn_Calc_Step2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_Calc_Step2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtn_Get_Last_Table, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_putValue_Step1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_Calc_Step2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_Calc_table_Newsday_Distribution, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_putValue_Step1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtn_Calc_Step2)
                .addGap(18, 18, 18)
                .addComponent(jbtn_Calc_table_Newsday_Distribution)
                .addGap(18, 18, 18)
                .addComponent(jbtn_Get_Last_Table, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jPanel4.setBackground(new java.awt.Color(0, 204, 255));

        btn_Draw.setBackground(new java.awt.Color(102, 0, 102));
        btn_Draw.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Draw.setForeground(new java.awt.Color(255, 255, 255));
        btn_Draw.setText("Draw");
        btn_Draw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DrawActionPerformed(evt);
            }
        });

        btn_Get_Excel.setBackground(new java.awt.Color(102, 0, 102));
        btn_Get_Excel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Get_Excel.setForeground(new java.awt.Color(255, 255, 255));
        btn_Get_Excel.setText("Get Excel");
        btn_Get_Excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Get_ExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Get_Excel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Draw, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btn_Draw, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btn_Get_Excel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 0));

        btn_putValue_From_Yourself.setBackground(new java.awt.Color(0, 102, 204));
        btn_putValue_From_Yourself.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_putValue_From_Yourself.setForeground(new java.awt.Color(255, 255, 255));
        btn_putValue_From_Yourself.setText("To enter Values yourself");
        btn_putValue_From_Yourself.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_putValue_From_YourselfActionPerformed(evt);
            }
        });

        btnTrueFalse.setBackground(new java.awt.Color(0, 102, 204));
        btnTrueFalse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTrueFalse.setForeground(new java.awt.Color(255, 255, 255));
        btnTrueFalse.setText("False");
        btnTrueFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrueFalseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_putValue_From_Yourself, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnTrueFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_putValue_From_Yourself, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrueFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jScrollPane4.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N

        Table_NewsdayWithRandomDigit_Type.setBackground(new java.awt.Color(96, 162, 41));
        Table_NewsdayWithRandomDigit_Type.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Table_NewsdayWithRandomDigit_Type.setForeground(new java.awt.Color(102, 0, 0));
        Table_NewsdayWithRandomDigit_Type.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null},
                {"", null, null, null, null},
                {"", null, null, null, null}
            },
            new String [] {
                "Type of Newsday", "Probability", "Cumulative", "From", "To"
            }
        ));
        Table_NewsdayWithRandomDigit_Type.setIntercellSpacing(new java.awt.Dimension(3, 3));
        jScrollPane4.setViewportView(Table_NewsdayWithRandomDigit_Type);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jScrollPane3.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N

        Table_Newsday_Distribution.setBackground(new java.awt.Color(255, 150, 8));
        Table_Newsday_Distribution.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Table_Newsday_Distribution.setForeground(new java.awt.Color(51, 0, 0));
        Table_Newsday_Distribution.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null},
                {"", null, null, null},
                {"", null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Demand", "Good", "Fair", "Poor"
            }
        ));
        Table_Newsday_Distribution.setIntercellSpacing(new java.awt.Dimension(3, 3));
        Table_Newsday_Distribution.setMinimumSize(new java.awt.Dimension(65, 222));
        Table_Newsday_Distribution.setPreferredSize(new java.awt.Dimension(150, 112));
        jScrollPane3.setViewportView(Table_Newsday_Distribution);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Probability");

        jScrollPane2.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N

        Table_New_Type.setBackground(new java.awt.Color(255, 150, 8));
        Table_New_Type.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Table_New_Type.setForeground(new java.awt.Color(51, 0, 0));
        Table_New_Type.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null},
                {"", null},
                {"", null}
            },
            new String [] {
                "Type of Newsday", "Probability"
            }
        ));
        Table_New_Type.setIntercellSpacing(new java.awt.Dimension(3, 3));
        jScrollPane2.setViewportView(Table_New_Type);

        jScrollPane1.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N

        Table_Limits.setBackground(new java.awt.Color(255, 150, 8));
        Table_Limits.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Table_Limits.setForeground(new java.awt.Color(51, 0, 0));
        Table_Limits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Days", "Q", "Cost", "Salvage"
            }
        ));
        jScrollPane1.setViewportView(Table_Limits);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(196, 196, 196))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btn_Show_info.setBackground(new java.awt.Color(0, 102, 0));
        btn_Show_info.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Show_info.setForeground(new java.awt.Color(255, 255, 255));
        btn_Show_info.setText("Show Information");
        btn_Show_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Show_infoActionPerformed(evt);
            }
        });

        btn_Exit.setBackground(new java.awt.Color(51, 51, 0));
        btn_Exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Exit.setForeground(new java.awt.Color(255, 255, 204));
        btn_Exit.setText("Exit");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1823, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane5)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(206, 206, 206)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Show_info))
                                .addGap(9, 9, 9))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btn_Show_info, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_putValue_Step1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_putValue_Step1ActionPerformed
try{
        if(arrData.bool==false){
        Table_New_Type.setValueAt("Good", 0, 0);
        Table_New_Type.setValueAt("Fair", 1, 0);
        Table_New_Type.setValueAt("Poor", 2, 0);
        
        Table_New_Type.setValueAt(0.35, 0, 1);
        Table_New_Type.setValueAt(0.45, 1, 1);
        Table_New_Type.setValueAt(0.20 , 2, 1);
        
        Table_Limits.setValueAt((int)20  , 0, 0);
        Table_Limits.setValueAt((int)70  , 0, 1);
        Table_Limits.setValueAt(0.17, 0, 2);
        Table_Limits.setValueAt(0.05, 0, 3);

        int m=40;
        for(int i=0;i<7;i++){
        Table_Newsday_Distribution.setValueAt(m, i, 0);
        m+=10;
        }
        Table_Newsday_Distribution.setValueAt(0.03, 0, 1);
        Table_Newsday_Distribution.setValueAt(0.05, 1, 1);
        Table_Newsday_Distribution.setValueAt(0.15, 2, 1);
        Table_Newsday_Distribution.setValueAt(0.20, 3, 1);
        Table_Newsday_Distribution.setValueAt(0.35, 4, 1);
        Table_Newsday_Distribution.setValueAt(0.15, 5, 1);
        Table_Newsday_Distribution.setValueAt(0.07, 6, 1);
        
        Table_Newsday_Distribution.setValueAt(0.10, 0, 2);
        Table_Newsday_Distribution.setValueAt(0.18, 1, 2);
        Table_Newsday_Distribution.setValueAt(0.40, 2, 2);
        Table_Newsday_Distribution.setValueAt(0.20, 3, 2);
        Table_Newsday_Distribution.setValueAt(0.08, 4, 2);
        Table_Newsday_Distribution.setValueAt(0.04, 5, 2);
        Table_Newsday_Distribution.setValueAt(0.00, 6, 2);
        
        Table_Newsday_Distribution.setValueAt(0.44, 0, 3);
        Table_Newsday_Distribution.setValueAt(0.22, 1, 3);
        Table_Newsday_Distribution.setValueAt(0.16, 2, 3);
        Table_Newsday_Distribution.setValueAt(0.12, 3, 3);
        Table_Newsday_Distribution.setValueAt(0.06, 4, 3);
        Table_Newsday_Distribution.setValueAt(0.00, 5, 3);
        Table_Newsday_Distribution.setValueAt(0.00, 6, 3);
}
else{
    for (int i = 0; i < 3; i++) {
        Table_New_Type.setValueAt(arrData.arrStr[i], i, 0);
    }
    for (int i = 0; i < 3; i++) {
        Table_New_Type.setValueAt(arrData.arrProbType[i], i, 1);
    }    
        
        Table_Limits.setValueAt((int)arrData.NumDays  , 0, 0);
        Table_Limits.setValueAt((int)arrData.Quantity  , 0, 1);
        Table_Limits.setValueAt(arrData.Cost, 0, 2);
        Table_Limits.setValueAt(arrData.Salvage, 0, 3);

        
        for(int i=0;i<7;i++){
        Table_Newsday_Distribution.setValueAt(arrData.arrDemand[i], i, 0);
        }
        for(int i=0;i<7;i++){
        Table_Newsday_Distribution.setValueAt(arrData.arrProbType1[i], i, 1);
        }
        for(int i=0;i<7;i++){
        Table_Newsday_Distribution.setValueAt(arrData.arrProbType2[i], i, 2);
        }
        for(int i=0;i<7;i++){
        Table_Newsday_Distribution.setValueAt(arrData.arrProbType3[i], i, 3);
        }
      
        
        
}
} 
        catch (Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
    }

    }//GEN-LAST:event_btn_putValue_Step1ActionPerformed

    private void jbtn_Calc_Step2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_Calc_Step2ActionPerformed
try{
    
for(int i=0;i<3;i++)
  {
    for(int j=0;j<2;j++)
      Table_NewsdayWithRandomDigit_Type.setValueAt(Table_New_Type.getValueAt(i, j), i, j);    
  }

for(int i=0;i<3;i++)
  {
   if(i==0)
       Table_NewsdayWithRandomDigit_Type.setValueAt(Table_NewsdayWithRandomDigit_Type.getValueAt(0, 1), 0, 2);
   else
       Table_NewsdayWithRandomDigit_Type.setValueAt((double)Table_NewsdayWithRandomDigit_Type.getValueAt(i, 1)+(double)Table_NewsdayWithRandomDigit_Type.getValueAt(i-1, 2), i, 2);
  }

for(int i=0;i<3;i++)
   Table_NewsdayWithRandomDigit_Type.setValueAt((int)(100*(double)Table_NewsdayWithRandomDigit_Type.getValueAt(i, 2)), i, 4);


for(int i=0;i<3;i++)
  {
    if(i==0)
        Table_NewsdayWithRandomDigit_Type.setValueAt(1,i,3);
    else
        Table_NewsdayWithRandomDigit_Type.setValueAt((int)(1+(int)Table_NewsdayWithRandomDigit_Type.getValueAt(i-1, 4)), i, 3);
  }
} 
        catch (Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
    }

    }//GEN-LAST:event_jbtn_Calc_Step2ActionPerformed

    
    private void jbtn_Calc_table_Newsday_DistributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_Calc_table_Newsday_DistributionActionPerformed
    try{
        
    for(int i=0;i<7;i++)
    {
       for(int j=0;j<4;j++)
          Table_N_Distrib_with_R_To_Type.setValueAt(Table_Newsday_Distribution.getValueAt(i, j), i, j);
    }

    for(int i=0;i<7;i++)
    {
      if(i==0)
        Table_N_Distrib_with_R_To_Type.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(0,1), 0, 4);
      else
        Table_N_Distrib_with_R_To_Type.setValueAt((double)Table_N_Distrib_with_R_To_Type.getValueAt(i-1, 4)+(double)Table_N_Distrib_with_R_To_Type.getValueAt(i, 1), i, 4);
    }
    
    for(int i=0;i<7;i++)
    {
      if(i==0)
        Table_N_Distrib_with_R_To_Type.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(0,2), 0, 5);
      else
         Table_N_Distrib_with_R_To_Type.setValueAt((double)Table_N_Distrib_with_R_To_Type.getValueAt(i-1, 5)+(double)Table_N_Distrib_with_R_To_Type.getValueAt(i, 2), i, 5);
    }
    
for(int i=0;i<7;i++)
{
    if(i==0)
        Table_N_Distrib_with_R_To_Type.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(0,3), 0, 6);
    else
        Table_N_Distrib_with_R_To_Type.setValueAt((double)Table_N_Distrib_with_R_To_Type.getValueAt(i-1, 6)+(double)Table_N_Distrib_with_R_To_Type.getValueAt(i, 3), i, 6);
}

for(int i=0;i<7;i++)
   Table_N_Distrib_with_R_To_Type.setValueAt((int)(100*(double)Table_N_Distrib_with_R_To_Type.getValueAt(i, 4)), i, 8);

for(int i=0;i<7;i++)
{
    if(i==0)
        Table_N_Distrib_with_R_To_Type.setValueAt(1,i,7);
    else
        Table_N_Distrib_with_R_To_Type.setValueAt(1+(int)Table_N_Distrib_with_R_To_Type.getValueAt(i-1, 8), i, 7);
}

for(int i=0;i<7;i++)
  Table_N_Distrib_with_R_To_Type.setValueAt((int)(100*(double)Table_N_Distrib_with_R_To_Type.getValueAt(i, 5)), i, 10);


for(int i=0;i<7;i++)
{
   if(i==0)
      Table_N_Distrib_with_R_To_Type.setValueAt(1,i,9);
   else
   Table_N_Distrib_with_R_To_Type.setValueAt(1+(int)Table_N_Distrib_with_R_To_Type.getValueAt(i-1, 10), i, 9);
}

for(int i=0;i<7;i++)
   Table_N_Distrib_with_R_To_Type.setValueAt((int)(100*(double)Table_N_Distrib_with_R_To_Type.getValueAt(i, 6)), i, 12);


for(int i=0;i<7;i++)
{
    if(i==0)
      Table_N_Distrib_with_R_To_Type.setValueAt(1,i,11);
    else
      Table_N_Distrib_with_R_To_Type.setValueAt(1+(int)Table_N_Distrib_with_R_To_Type.getValueAt(i-1, 12), i, 11);
}

} 
    catch (Exception ex)
    {
            JOptionPane.showMessageDialog(null,ex.getMessage());
    }

    }//GEN-LAST:event_jbtn_Calc_table_Newsday_DistributionActionPerformed

    
    private void jbtn_Get_Last_TableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_Get_Last_TableActionPerformed

try{    
    for(int i=0;i<20;i++)       
        Table_Total.setValueAt(i+1, i, 0);


for(int i=0;i<20;i++) 
{
    int n = (int)(1+(Math.random()*100));
    Table_Total.setValueAt(n, i, 1); 
}

for(int i=0;i<20;i++)
{ 
    if((((int)Table_Total.getValueAt(i,1) > (int)Table_NewsdayWithRandomDigit_Type.getValueAt(0,3))||((int)Table_Total.getValueAt(i,1) == (int)Table_NewsdayWithRandomDigit_Type.getValueAt(0,3)))&&(((int)Table_Total.getValueAt(i,1) < (int)Table_NewsdayWithRandomDigit_Type.getValueAt(0,4))||((int)Table_Total.getValueAt(i,1) == (int)Table_NewsdayWithRandomDigit_Type.getValueAt(0,4)))) {
      Table_Total.setValueAt(Table_New_Type.getValueAt(0, 0), i, 2);
    }
    if((((int)Table_Total.getValueAt(i,1) > (int)Table_NewsdayWithRandomDigit_Type.getValueAt(1,3))||((int)Table_Total.getValueAt(i,1) == (int)Table_NewsdayWithRandomDigit_Type.getValueAt(1,3)))&&(((int)Table_Total.getValueAt(i,1) < (int)Table_NewsdayWithRandomDigit_Type.getValueAt(1,4))||((int)Table_Total.getValueAt(i,1) == (int)Table_NewsdayWithRandomDigit_Type.getValueAt(1,4)))) {  
      Table_Total.setValueAt(Table_New_Type.getValueAt(1, 0), i, 2);
    }
    if((((int)Table_Total.getValueAt(i,1) > (int)Table_NewsdayWithRandomDigit_Type.getValueAt(2,3))||((int)Table_Total.getValueAt(i,1) == (int)Table_NewsdayWithRandomDigit_Type.getValueAt(2,3)))&&(((int)Table_Total.getValueAt(i,1) < (int)Table_NewsdayWithRandomDigit_Type.getValueAt(2,4))||((int)Table_Total.getValueAt(i,1) == (int)Table_NewsdayWithRandomDigit_Type.getValueAt(2,4)))) { 
      Table_Total.setValueAt(Table_New_Type.getValueAt(2, 0), i, 2);
    }
}

for(int i=0;i<20;i++) 
{
    int n = (int)(1+(Math.random()*100));
        Table_Total.setValueAt(n, i, 3); 
}
 
for(int i=0;i<20;i++) 
{
  if((Table_Total.getValueAt(i, 2)).equals(Table_New_Type.getValueAt(0,0)))
  {
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(0,7))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(0,7)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(0,8))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(0,8)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(0, 0), i, 4);
      }
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(1,7))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(1,7)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(1,8))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(1,8)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(1, 0), i, 4);
      }
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(2,7))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(2,7)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(2,8))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(2,8)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(2, 0), i, 4);
      }
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(3,7))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(3,7)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(3,8))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(3,8)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(3, 0), i, 4);
      }
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(4,7))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(4,7)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(4,8))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(4,8)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(4, 0), i, 4);
      }
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(5,7))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(5,7)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(5,8))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(5,8)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(5, 0), i, 4);
      }
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(6,7))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(6,7)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(6,8))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(6,8)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(6, 0), i, 4);
      }
   }

  
   if((Table_Total.getValueAt(i, 2)).equals(Table_New_Type.getValueAt(1,0))){
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(0,9))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(0,9)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(0,10))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(0,10)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(0, 0), i, 4);
      }
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(1,9))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(1,9)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(1,10))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(1,10)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(1, 0), i, 4);
      }
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(2,9))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(2,9)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(2,10))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(2,10)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(2, 0), i, 4);
      }
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(3,9))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(3,9)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(3,10))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(3,10)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(3, 0), i, 4);
      }
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(4,9))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(4,9)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(4,10))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(4,10)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(4, 0), i, 4);
      }
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(5,9))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(5,9)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(5,10))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(5,10)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(5, 0), i, 4);
      }
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(6,9))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(6,9)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(6,10))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(6,10)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(6, 0), i, 4);
      }
      
   }

   if((Table_Total.getValueAt(i, 2)).equals(Table_New_Type.getValueAt(2,0))){
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(0,11))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(0,11)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(0,12))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(0,12)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(0, 0), i, 4);
      }
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(1,11))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(1,11)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(1,12))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(1,12)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(1, 0), i, 4);
      }
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(2,11))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(2,11)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(2,12))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(2,12)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(2, 0), i, 4);
      }
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(3,11))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(3,11)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(3,12))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(3,12)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(3, 0), i, 4);
      }
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(4,11))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(4,11)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(4,12))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(4,12)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(4, 0), i, 4);
      }
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(5,11))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(5,11)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(5,12))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(5,12)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(5, 0), i, 4);
      }
      if((((int)Table_Total.getValueAt(i,3) > (int)Table_N_Distrib_with_R_To_Type.getValueAt(6,11))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(6,11)))&&(((int)Table_Total.getValueAt(i,3) < (int)Table_N_Distrib_with_R_To_Type.getValueAt(6,12))||((int)Table_Total.getValueAt(i,3) == (int)Table_N_Distrib_with_R_To_Type.getValueAt(6,12)))) {  
        Table_Total.setValueAt(Table_N_Distrib_with_R_To_Type.getValueAt(6, 0), i, 4);
      }
      
    }
   
}

for(int i=0;i<20;i++)
{
   if((int)Table_Total.getValueAt(i, 4) > (int)Table_Limits.getValueAt(0,1))
    {
        Table_Total.setValueAt((int)(Table_Limits.getValueAt(0,1) )*(double)( Table_Limits.getValueAt(0,2)), i, 5);
        Table_Total.setValueAt(((int)Table_Total.getValueAt(i, 4) - (int)Table_Limits.getValueAt(0,1))*(double)( Table_Limits.getValueAt(0,2)), i, 6);
        Table_Total.setValueAt((double)0, i, 7);
    }
   else{
        Table_Total.setValueAt(((int)Table_Total.getValueAt(i,4) * (double)Table_Limits.getValueAt(0,2)), i, 5);
        Table_Total.setValueAt((double)0, i, 6);
        if((int)Table_Total.getValueAt(i, 4) < (int)Table_Limits.getValueAt(0,1))
            Table_Total.setValueAt(((int)Table_Limits.getValueAt(0,1)-(int)Table_Total.getValueAt(i, 4))*(double)Table_Limits.getValueAt(0,3), i, 7);
        else
            Table_Total.setValueAt((double)0, i, 7);

       }
   
}

for (int i = 0; i < 20; i++) 
{
    Table_Total.setValueAt(((double)Table_Total.getValueAt(i, 5)+(double)Table_Total.getValueAt(i, 7)-(double)Table_Total.getValueAt(i, 6)), i, 8);
  
    if((int)Table_Total.getValueAt(i, 4) < (int)Table_Limits.getValueAt(0,1))
        Table_Total.setValueAt((int)Table_Limits.getValueAt(0,1)-(int)Table_Total.getValueAt(i, 4) , i, 9);
    else
        Table_Total.setValueAt( 0, i, 9);
    
    Table_Total.setValueAt( (double)Table_Total.getValueAt(i, 5)+(double)Table_Total.getValueAt(i, 7), i, 10);
    
    if((int)Table_Total.getValueAt(i, 4) < (int)Table_Limits.getValueAt(0,1))
        Table_Total.setValueAt(((int)Table_Limits.getValueAt(0,1)-(int)Table_Total.getValueAt(i, 4))*((double)Table_Limits.getValueAt(0,2)-(double)Table_Limits.getValueAt(0,3)) , i, 11);
    else
        Table_Total.setValueAt((double)0, i, 11);

    Table_Total.setValueAt( (double)Table_Total.getValueAt(i, 11)+(double)Table_Total.getValueAt(i, 6), i, 12);

}
 
} 
    catch (Exception ex)
    {
            JOptionPane.showMessageDialog(null,ex.getMessage());
    }

    }//GEN-LAST:event_jbtn_Get_Last_TableActionPerformed

    private void btn_putValue_From_YourselfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_putValue_From_YourselfActionPerformed
    try
    {
        FRM_Set_Value_From_Yourself f =new FRM_Set_Value_From_Yourself();
    f.setVisible(true);
    f.setLocationRelativeTo(null);
    f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    } 
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    
    }//GEN-LAST:event_btn_putValue_From_YourselfActionPerformed

    private void btnTrueFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrueFalseActionPerformed
try{
if(btnTrueFalse.getText().equals("True"))
    {
     btnTrueFalse.setText("False");
     arrData.bool=false;
    }
else
    {
     btnTrueFalse.setText("True");
     arrData.bool=true;
    }
  
} 
        catch (Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
    }

    }//GEN-LAST:event_btnTrueFalseActionPerformed

    private void btn_DrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DrawActionPerformed
         
    try{
            Frm_Draw f2 =new Frm_Draw();
            myDrow d =new myDrow(f2);
            /////////////////////////////////////
            int Q =arrData.Quantity;
            double des =100+(Q*5);
            
            d.line(50,des,1100,des,Color.black);
            
            for(int i= 100;i<=1050;i+=50)
            {
                d.line(i, des-5, i, des+5,Color.black);
            }
            d.line(50, 650, 50, 50,Color.black);
            d.line(1050, 650, 1050, 50,Color.black);
           
            for(int i= 600;i>=100;i-=50)
            {
                d.line(45, i, 55, i,Color.black);
            }
            for(int i= 600;i>=100;i-=50)
            {
                d.line(1045, i, 1055, i,Color.black);
            }
            for(int i=0,j=50;i<20;i++,j+=50)
            {
            d.line(j  , 100, j+50, 100+5*((int)Table_Total.getValueAt(i, 4)), Color.red);
             if(i!=19)
              d.line(j+50, 100, j+50, 100+5*((int)Table_Total.getValueAt(i, 4)), Color.BLACK);
            }
            
            JLabel L0=new JLabel("0");
            JLabel L1=new JLabel("1");
            JLabel L2=new JLabel("2");
            JLabel L3=new JLabel("3");
            JLabel L4=new JLabel("4");
            JLabel L5=new JLabel("5");
            JLabel L6=new JLabel("6");
            JLabel L7=new JLabel("7");
            JLabel L8=new JLabel("8");
            JLabel L9=new JLabel("9");
            JLabel L10=new JLabel("10");
            JLabel L11=new JLabel("11");
            JLabel L12=new JLabel("12");
            JLabel L13=new JLabel("13");
            JLabel L14=new JLabel("14");
            JLabel L15=new JLabel("15");
            JLabel L16=new JLabel("16");
            JLabel L17=new JLabel("17");
            JLabel L18=new JLabel("18");
            JLabel L19=new JLabel("19");
            JLabel L20=new JLabel("20");
            
            L0.setBounds(0,0, 50, 50);
            L1.setBounds(0,0, 50, 50);
            L2.setBounds(0,0, 50, 50);
            L3.setBounds(0,0, 50, 50);
            L4.setBounds(0,0, 50, 50);
            L5.setBounds(0,0, 50, 50);
            L6.setBounds(0,0, 50, 50);
            L7.setBounds(0,0, 50, 50);
            L8.setBounds(0,0, 50, 50);
            L9.setBounds(0,0, 50, 50);
            L10.setBounds(0,0, 50, 50);
            L11.setBounds(0,0, 50, 50);
            L12.setBounds(0,0, 50, 50);
            L13.setBounds(0,0, 50, 50);
            L14.setBounds(0,0, 50, 50);
            L15.setBounds(0,0, 50, 50);
            L16.setBounds(0,0, 50, 50);
            L17.setBounds(0,0, 50, 50);
            L18.setBounds(0,0, 50, 50);
            L19.setBounds(0,0, 50, 50);
            L20.setBounds(0,0, 50, 50);
            
            L0.setLocation(50 -3, (int) (des+5));
            L1.setLocation(100-3, (int) (des+5));
            L2.setLocation(150-3, (int) (des+5));
            L3.setLocation(200-3, (int) (des+5));
            L4.setLocation(250-3, (int) (des+5));
            L5.setLocation(300-3, (int) (des+5));
            L6.setLocation(350-3, (int) (des+5));
            L7.setLocation(400-3, (int) (des+5));
            L8.setLocation(450-3, (int) (des+5));
            L9.setLocation(500-3, (int) (des+5));
            L10.setLocation(550-6, (int) (des+5));
            L11.setLocation(600-6, (int) (des+5));
            L12.setLocation(650-6, (int) (des+5));
            L13.setLocation(700-6, (int) (des+5));
            L14.setLocation(750-6, (int) (des+5));
            L15.setLocation(800-6, (int) (des+5));
            L16.setLocation(850-6, (int) (des+5));
            L17.setLocation(900-6, (int) (des+5));
            L18.setLocation(950-6, (int) (des+5));
            L19.setLocation(1000-6, (int) (des+5));
            L20.setLocation(1050-6, (int) (des+5));
            
            f2.add(L0);
            f2.add(L1);
            f2.add(L2);
            f2.add(L3);
            f2.add(L4);
            f2.add(L5);
            f2.add(L6);
            f2.add(L7);
            f2.add(L8);
            f2.add(L9);
            f2.add(L10);
            f2.add(L11);
            f2.add(L12);
            f2.add(L13);
            f2.add(L14);
            f2.add(L15);
            f2.add(L16);
            f2.add(L17);
            f2.add(L18);
            f2.add(L19);
            f2.add(L20);
            
            JLabel Ll0=new JLabel("0");
            JLabel Ll1=new JLabel("1");
            JLabel Ll2=new JLabel("2");
            JLabel Ll3=new JLabel("3");
            JLabel Ll4=new JLabel("4");
            JLabel Ll5=new JLabel("5");
            JLabel Ll6=new JLabel("6");
            JLabel Ll7=new JLabel("7");
            JLabel Ll8=new JLabel("8");
            JLabel Ll9=new JLabel("9");
            JLabel Ll10=new JLabel("10");
            Ll0.setBounds(0,0, 50, 50);
            Ll1.setBounds(0,0, 50, 50);
            Ll2.setBounds(0,0, 50, 50);
            Ll3.setBounds(0,0, 50, 50);
            Ll4.setBounds(0,0, 50, 50);
            Ll5.setBounds(0,0, 50, 50);
            Ll6.setBounds(0,0, 50, 50);
            Ll7.setBounds(0,0, 50, 50);
            Ll8.setBounds(0,0, 50, 50);
            Ll9.setBounds(0,0, 50, 50);
            Ll10.setBounds(0,0, 50, 50);
            Ll0.setLocation(25,  75);
            Ll1.setLocation(25, 125);
            Ll2.setLocation(25, 175);
            Ll3.setLocation(25, 225);
            Ll4.setLocation(25, 275);
            Ll5.setLocation(25, 325);
            Ll6.setLocation(25, 375);
            Ll7.setLocation(25, 425);
            Ll8.setLocation(25, 475);
            Ll9.setLocation(25, 525);
            Ll10.setLocation(25,575);
            f2.add(Ll0);
            f2.add(Ll1);
            f2.add(Ll2);
            f2.add(Ll3);
            f2.add(Ll4);
            f2.add(Ll5);
            f2.add(Ll6);
            f2.add(Ll7);
            f2.add(Ll8);
            f2.add(Ll9);
            f2.add(Ll10);
            
            JLabel Lr0=new JLabel("0");
            JLabel Lr1=new JLabel("1");
            JLabel Lr2=new JLabel("2");
            JLabel Lr3=new JLabel("3");
            JLabel Lr4=new JLabel("4");
            JLabel Lr5=new JLabel("5");
            JLabel Lr6=new JLabel("6");
            JLabel Lr7=new JLabel("7");
            JLabel Lr8=new JLabel("8");
            JLabel Lr9=new JLabel("9");
            JLabel Lr10=new JLabel("10");
            Lr0.setBounds(0,0, 50, 50);
            Lr1.setBounds(0,0, 50, 50);
            Lr2.setBounds(0,0, 50, 50);
            Lr3.setBounds(0,0, 50, 50);
            Lr4.setBounds(0,0, 50, 50);
            Lr5.setBounds(0,0, 50, 50);
            Lr6.setBounds(0,0, 50, 50);
            Lr7.setBounds(0,0, 50, 50);
            Lr8.setBounds(0,0, 50, 50);
            Lr9.setBounds(0,0, 50, 50);
            Lr10.setBounds(0,0, 50, 50);
            Lr0.setLocation(1075,  75);
            Lr1.setLocation(1075, 125);
            Lr2.setLocation(1075, 175);
            Lr3.setLocation(1075, 225);
            Lr4.setLocation(1075, 275);
            Lr5.setLocation(1075, 325);
            Lr6.setLocation(1075, 375);
            Lr7.setLocation(1075, 425);
            Lr8.setLocation(1075, 475);
            Lr9.setLocation(1075, 525);
            Lr10.setLocation(1075,575);
            
            f2.add(Lr0);
            f2.add(Lr1);
            f2.add(Lr2);
            f2.add(Lr3);
            f2.add(Lr4);
            f2.add(Lr5);
            f2.add(Lr6);
            f2.add(Lr7);
            f2.add(Lr8);
            f2.add(Lr9);
            f2.add(Lr10);
            
            f2.setVisible(true);
            f2.setLocationRelativeTo(null);
            f2.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            d.border=2;
            } 
        catch (Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
    }
            
    }//GEN-LAST:event_btn_DrawActionPerformed

    private void btn_Get_ExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Get_ExcelActionPerformed
 
    String exelFolder = "C:\\Users\\ATD\\Desktop\\";
    String filepath  = exelFolder +"Simulation of Inventory Systems.xlsx" ; 
try{
    
    FileOutputStream fos = new FileOutputStream(filepath);
    XSSFWorkbook workbook =new XSSFWorkbook();
    XSSFSheet sheet =  workbook.createSheet("First Sheet");

    Row r = sheet.createRow(1);
        Cell c =r.createCell(3);
        c.setCellValue("Newsday\n Type");
        r=sheet.createRow(2);
        c =r.createCell(1);
        c.setCellValue("Type of\n Newsdays");
        c =r.createCell(2);
        c.setCellValue("Probability");
        c =r.createCell(3);
        c.setCellValue("Cumulative\n Probability ");
        c =r.createCell(4);
        c.setCellValue("From");
        c =r.createCell(5);
        c.setCellValue("To");
       
    for (int i = 0; i < 3; i++) 
    {
        for (int j = 0; j < 5; j++)
             arrData.table1[i][j]= String.valueOf(Table_NewsdayWithRandomDigit_Type.getValueAt(i, j)) ;
    }
    for (int i = 0; i < 7; i++) 
    {
        for (int j = 0; j < 13;j++)
             arrData.table2[i][j]= String.valueOf(Table_N_Distrib_with_R_To_Type.getValueAt(i, j)) ;
    }
    for(int i=0;i<3;i++)
    {
        r=sheet.createRow(4+i);
        for(int j=0;j<5;j++)
        {
            c=r.createCell(j+1);
            if(j==0)
                  c.setCellValue(arrData.table1[i][j]);
            else
            c.setCellValue(Double.valueOf(arrData.table1[i][j]));
        }
    }
        r=sheet.createRow(8);
        c =r.createCell(6);
        c.setCellValue("Newsday\n Distribution");
        r=sheet.createRow(9);
        c =r.createCell(1);
        c.setCellValue("Demand");
        c =r.createCell(2);
        c.setCellValue("Prob\n Good");
        c =r.createCell(3);
        c.setCellValue("Prob\n Fair");
        c =r.createCell(4);
        c.setCellValue("Prob\n Poor");
        c =r.createCell(5);
        c.setCellValue("Cumulative\n Good");
        c =r.createCell(6);
        c.setCellValue("Cumulative\n Fair");
        c =r.createCell(7);
        c.setCellValue("Cumulative \nPoor");
        c =r.createCell(8);
        c.setCellValue("From\n Poor");
        c =r.createCell(9);
        c.setCellValue("To\n Poor");
        c =r.createCell(10);
        c.setCellValue("From\n Poor");
        c =r.createCell(11);
        c.setCellValue("To\n Poor");
        c =r.createCell(12);
        c.setCellValue("From\n Poor");
        c =r.createCell(13);
        c.setCellValue("To\n Poor");
       for (int i = 0; i < 20; i++) 
       {
          for (int j = 0; j < 13;j++)
             arrData.table4[i][j]= String.valueOf(Table_Total.getValueAt(i, j)) ;
       }
        for(int i=0;i<7;i++)
        {
          r=sheet.createRow(11+i);
          for(int j=0;j<13;j++)
           {
            c=r.createCell(j+1);
            c.setCellValue(Double.valueOf(arrData.table2[i][j]));
           }
        }  
        r=sheet.getRow(2);
        c=r.createCell(8);
        c.setCellValue("Limits");
        r=sheet.getRow(4);
        c=r.createCell(7);
        c.setCellValue("Days");
        c=r.createCell(8);
        c.setCellValue("Quantity");
        c=r.createCell(9);
        c.setCellValue("Cost");
        c=r.createCell(10);
        c.setCellValue("Salvage");
        for(int i=0;i<4;i++)
            arrData.table3[i]=String.valueOf(Table_Limits.getValueAt(0, i));
                r=sheet.getRow(5);
        for(int i=0;i<4;i++)
        {
          c=r.createCell(7+i);          
          c.setCellValue(Double.valueOf(arrData.table3[i]));
        }
        r=sheet.createRow(19);
        c =r.createCell(1);
        c.setCellValue("Day");
        c =r.createCell(2);
        c.setCellValue("R.D.for\n Type of\n Newsday");
        c =r.createCell(3);
        c.setCellValue("Type of\n Newsday");
        c =r.createCell(4);
        c.setCellValue("R.D.for\n Demand");
        c =r.createCell(5);
        c.setCellValue("Demand");
        c =r.createCell(6);
        c.setCellValue("Revenue \nfrom\n Sales");
        c =r.createCell(7);
        c.setCellValue("Lost Profit\n from Excess\n Demand");
        c =r.createCell(8);
        c.setCellValue("Salvage \nfrom Sale \nof Scrap");
        c =r.createCell(9);
        c.setCellValue("Daily\n Profit");
        c =r.createCell(10);
        c.setCellValue("#of \nRemaining\n Newspapers");
        c =r.createCell(11);
        c.setCellValue("Net \nProfit");
        c =r.createCell(12);
        c.setCellValue("True \nLost");
        c =r.createCell(13);
        c.setCellValue("Full \nTrue\n Lost");
        
        for(int i=0;i<20;i++)
        {
         r=sheet.createRow(21+i);
         for(int j=0;j<13;j++)
          {
            c=r.createCell(j+1);
            if(j==2)
               c.setCellValue( arrData.table4[i][j]);
             else   
            c.setCellValue(Double.valueOf(arrData.table4[i][j]));
          }
        }  
        workbook.write(fos);
        workbook.close();
        JOptionPane.showMessageDialog(null,"Excel Saved on C:\\Users\\ATD\\Desktop\\");

}    
catch (Exception ex) 
{
  JOptionPane.showMessageDialog(null,ex.getMessage());

} 


    }//GEN-LAST:event_btn_Get_ExcelActionPerformed

    private void btn_Show_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Show_infoActionPerformed

  try
  {
       FRM_information f =new FRM_information();
       f.setVisible(true);
       f.setLocationRelativeTo(null);
       f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
  } 
        catch (Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
    }// TODO add your handling code here:
    }//GEN-LAST:event_btn_Show_infoActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed

System.exit(0);        
// TODO add your handling code here:
    }//GEN-LAST:event_btn_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_investory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_investory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_investory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_investory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_investory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Limits;
    private javax.swing.JTable Table_N_Distrib_with_R_To_Type;
    private javax.swing.JTable Table_New_Type;
    private javax.swing.JTable Table_NewsdayWithRandomDigit_Type;
    private javax.swing.JTable Table_Newsday_Distribution;
    private javax.swing.JTable Table_Total;
    private javax.swing.JButton btnTrueFalse;
    private javax.swing.JButton btn_Draw;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Get_Excel;
    private javax.swing.JButton btn_Show_info;
    private javax.swing.JButton btn_putValue_From_Yourself;
    private javax.swing.JButton btn_putValue_Step1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton jbtn_Calc_Step2;
    private javax.swing.JButton jbtn_Calc_table_Newsday_Distribution;
    private javax.swing.JButton jbtn_Get_Last_Table;
    // End of variables declaration//GEN-END:variables
}
