/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Single_Server;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GraphicsConfiguration;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author ATD
 */
public class FRM_Begin extends javax.swing.JFrame {
    /**
     * Creates new form Form1
     */
    public FRM_Begin() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        JlblDuration3 = new javax.swing.JLabel();
        txtOP4 = new javax.swing.JTextField();
        txtOP8 = new javax.swing.JTextField();
        txtOP3 = new javax.swing.JTextField();
        txtOP2 = new javax.swing.JTextField();
        txtOP5 = new javax.swing.JTextField();
        txtOP7 = new javax.swing.JTextField();
        txtOP6 = new javax.swing.JTextField();
        txtOP1 = new javax.swing.JTextField();
        arrtime2 = new javax.swing.JLabel();
        arrTime6 = new javax.swing.JTextField();
        arrTime5 = new javax.swing.JTextField();
        arrTime4 = new javax.swing.JTextField();
        arrTime2 = new javax.swing.JTextField();
        serTime6 = new javax.swing.JTextField();
        serTime4 = new javax.swing.JTextField();
        JlblDuration = new javax.swing.JLabel();
        arrTime3 = new javax.swing.JTextField();
        serTime8 = new javax.swing.JTextField();
        arrTime8 = new javax.swing.JTextField();
        arrTime7 = new javax.swing.JTextField();
        serTime1 = new javax.swing.JTextField();
        serTime3 = new javax.swing.JTextField();
        serTime2 = new javax.swing.JTextField();
        arrTime1 = new javax.swing.JTextField();
        serTime5 = new javax.swing.JTextField();
        arrtime = new javax.swing.JLabel();
        serTime7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNM1 = new javax.swing.JTextField();
        arrtime1 = new javax.swing.JLabel();
        txtNM7 = new javax.swing.JTextField();
        txtNM6 = new javax.swing.JTextField();
        txtNM5 = new javax.swing.JTextField();
        txtNM4 = new javax.swing.JTextField();
        txtNM2 = new javax.swing.JTextField();
        txtNM8 = new javax.swing.JTextField();
        txtNM3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_Go_prob = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btn_rrrrrrrr1 = new javax.swing.JButton();
        btn_mmmmm2 = new javax.swing.JButton();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 102));
        setForeground(new java.awt.Color(255, 204, 51));
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btn4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn4MouseMoved(evt);
            }
        });
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn3MouseMoved(evt);
            }
        });
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn1MouseMoved(evt);
            }
        });

        btn2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn2MouseMoved(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 155, 26));

        JlblDuration3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JlblDuration3.setText("OP type");

        txtOP4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtOP4.setToolTipText("Enter the type of operation أدخل نوع العملية");
        txtOP4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOP4KeyTyped(evt);
            }
        });

        txtOP8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtOP8.setToolTipText("Enter the type of operation أدخل نوع العملية");
        txtOP8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOP8KeyTyped(evt);
            }
        });

        txtOP3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtOP3.setToolTipText("Enter the type of operation أدخل نوع العملية");
        txtOP3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOP3KeyTyped(evt);
            }
        });

        txtOP2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtOP2.setToolTipText("Enter the type of operation أدخل نوع العملية");
        txtOP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOP2ActionPerformed(evt);
            }
        });
        txtOP2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOP2KeyTyped(evt);
            }
        });

        txtOP5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtOP5.setToolTipText("Enter the type of operation أدخل نوع العملية");
        txtOP5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOP5KeyTyped(evt);
            }
        });

        txtOP7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtOP7.setToolTipText("Enter the type of operation أدخل نوع العملية");
        txtOP7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOP7KeyTyped(evt);
            }
        });

        txtOP6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtOP6.setToolTipText("Enter the type of operation أدخل نوع العملية");
        txtOP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOP6ActionPerformed(evt);
            }
        });
        txtOP6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOP6KeyTyped(evt);
            }
        });

        txtOP1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtOP1.setToolTipText("Enter the type of operation\nأدخل نوع العملية");
        txtOP1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOP1KeyTyped(evt);
            }
        });

        arrtime2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        arrtime2.setText("No");

        arrTime6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        arrTime6.setToolTipText("Enter customer arrival time #6\nادخل وقت وصول العميل رقم 6  ");
        arrTime6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                arrTime6KeyTyped(evt);
            }
        });

        arrTime5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        arrTime5.setToolTipText("Enter customer arrival time #5\nادخل وقت وصول العميل رقم 5  ");
        arrTime5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                arrTime5KeyTyped(evt);
            }
        });

        arrTime4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        arrTime4.setToolTipText("Enter customer arrival time #4\nادخل وقت وصول العميل رقم 4  ");
        arrTime4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                arrTime4KeyTyped(evt);
            }
        });

        arrTime2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        arrTime2.setToolTipText("Enter customer arrival time #2\nادخل وقت وصول العميل رقم 2  ");
        arrTime2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrTime2ActionPerformed(evt);
            }
        });
        arrTime2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                arrTime2KeyTyped(evt);
            }
        });

        serTime6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        serTime6.setToolTipText("Enter the time spent by Customer No.6 in the system\nأدخل الوقت الذى قضاه العميل رقم 6 فى النظام");
        serTime6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serTime6ActionPerformed(evt);
            }
        });
        serTime6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                serTime6KeyTyped(evt);
            }
        });

        serTime4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        serTime4.setToolTipText("Enter the time spent by Customer No.4 in the system\nأدخل الوقت الذى قضاه العميل رقم 4 فى النظام");
        serTime4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                serTime4KeyTyped(evt);
            }
        });

        JlblDuration.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JlblDuration.setText("Duration");

        arrTime3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        arrTime3.setToolTipText("Enter customer arrival time #3\nادخل وقت وصول العميل رقم 3  ");
        arrTime3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                arrTime3KeyTyped(evt);
            }
        });

        serTime8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        serTime8.setToolTipText("Enter the time spent by Customer No.8 in the system\nأدخل الوقت الذى قضاه العميل رقم 8 فى النظام");
        serTime8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                serTime8KeyTyped(evt);
            }
        });

        arrTime8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        arrTime8.setToolTipText("Enter customer arrival time #8\nادخل وقت وصول العميل رقم 8  ");
        arrTime8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrTime8ActionPerformed(evt);
            }
        });
        arrTime8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                arrTime8KeyTyped(evt);
            }
        });

        arrTime7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        arrTime7.setToolTipText("Enter customer arrival time #7\nادخل وقت وصول العميل رقم 7  ");
        arrTime7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrTime7ActionPerformed(evt);
            }
        });
        arrTime7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                arrTime7KeyTyped(evt);
            }
        });

        serTime1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        serTime1.setToolTipText("Enter the time spent by Customer No.1 in the system\nأدخل الوقت الذى قضاه العميل رقم 1 فى النظام");
        serTime1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                serTime1KeyTyped(evt);
            }
        });

        serTime3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        serTime3.setToolTipText("Enter the time spent by Customer No.3 in the system\nأدخل الوقت الذى قضاه العميل رقم 3 فى النظام");
        serTime3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                serTime3KeyTyped(evt);
            }
        });

        serTime2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        serTime2.setToolTipText("Enter the time spent by Customer No.2 in the system\nأدخل الوقت الذى قضاه العميل رقم 2 فى النظام");
        serTime2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                serTime2KeyTyped(evt);
            }
        });

        arrTime1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        arrTime1.setToolTipText("Enter customer arrival time #1\nادخل وقت وصول العميل رقم 1  ");
        arrTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrTime1ActionPerformed(evt);
            }
        });
        arrTime1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                arrTime1KeyTyped(evt);
            }
        });

        serTime5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        serTime5.setToolTipText("Enter the time spent by Customer No.5 in the system\nأدخل الوقت الذى قضاه العميل رقم 5 فى النظام");
        serTime5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                serTime5KeyTyped(evt);
            }
        });

        arrtime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        arrtime.setText("Arrival Time");

        serTime7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        serTime7.setToolTipText("Enter the time spent by Customer No.7 in the system\nأدخل الوقت الذى قضاه العميل رقم 7 فى النظام");
        serTime7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                serTime7KeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Single-Server Queue");

        txtNM1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNM1.setToolTipText("Enter cusromer name No. 1\nادخل إسم العميل رقم 1  ");
        txtNM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNM1ActionPerformed(evt);
            }
        });
        txtNM1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNM1KeyTyped(evt);
            }
        });

        arrtime1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        arrtime1.setText("Name");

        txtNM7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNM7.setToolTipText("Enter cusromer name No. 7\nادخل إسم العميل رقم 7\n");
        txtNM7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNM7ActionPerformed(evt);
            }
        });
        txtNM7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNM7KeyTyped(evt);
            }
        });

        txtNM6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNM6.setToolTipText("Enter cusromer name No. 6\nادخل إسم العميل رقم 6");
        txtNM6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNM6KeyTyped(evt);
            }
        });

        txtNM5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNM5.setToolTipText("Enter cusromer name No. 5\nادخل إسم العميل رقم 5");
        txtNM5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNM5KeyTyped(evt);
            }
        });

        txtNM4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNM4.setToolTipText("Enter cusromer name No. 4\nادخل إسم العميل رقم 4");
        txtNM4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNM4KeyTyped(evt);
            }
        });

        txtNM2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNM2.setToolTipText("Enter cusromer name No. 2\nادخل إسم العميل رقم2 ");
        txtNM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNM2ActionPerformed(evt);
            }
        });
        txtNM2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNM2KeyTyped(evt);
            }
        });

        txtNM8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNM8.setToolTipText("Enter cusromer name No. 8\nادخل إسم العميل رقم 8");
        txtNM8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNM8KeyTyped(evt);
            }
        });

        txtNM3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNM3.setToolTipText("Enter cusromer name No. 3\nادخل إسم العميل رقم 3");
        txtNM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNM3ActionPerformed(evt);
            }
        });
        txtNM3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNM3KeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("5-");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("8-");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("2-");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("4-");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("3-");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("6-");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("7-");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("1-");

        jPanel2.setBackground(new java.awt.Color(251, 80, 5));

        jButton3.setBackground(java.awt.Color.blue);
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Exit");
        jButton3.setToolTipText("Click here to Exit \n لإغلاق البرنامج");
        jButton3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton3StateChanged(evt);
            }
        });
        jButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton3MouseMoved(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setBackground(java.awt.Color.blue);
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Modify");
        jButton7.setToolTipText("Click here to modify the data\n  إضغط هنا لكى يتم تعديل البيانات");
        jButton7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton7StateChanged(evt);
            }
        });
        jButton7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton7MouseMoved(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton1.setBackground(java.awt.Color.blue);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("OK");
        jButton1.setToolTipText("Click here to calculate the output\n  إضغط هنا لكى يتم حساب الناتج");
        jButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton1StateChanged(evt);
            }
        });
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jButton1MouseWheelMoved(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_Go_prob.setBackground(java.awt.Color.blue);
        btn_Go_prob.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_Go_prob.setForeground(new java.awt.Color(255, 255, 255));
        btn_Go_prob.setText("Go to Probability");
        btn_Go_prob.setToolTipText("Click here for random data to be represented\n إضغط هنا لكى يتم تمثيل البيانات عشوائى");
        btn_Go_prob.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btn_Go_probStateChanged(evt);
            }
        });
        btn_Go_prob.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_Go_probMouseMoved(evt);
            }
        });
        btn_Go_prob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Go_probActionPerformed(evt);
            }
        });

        jButton4.setBackground(java.awt.Color.blue);
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Clear");
        jButton4.setToolTipText("Click here to clean the data\n  إضغط هنا لكى يتم تنظيف البيانات");
        jButton4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton4StateChanged(evt);
            }
        });
        jButton4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton4MouseMoved(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btn_rrrrrrrr1.setBackground(java.awt.Color.blue);
        btn_rrrrrrrr1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_rrrrrrrr1.setForeground(new java.awt.Color(255, 255, 255));
        btn_rrrrrrrr1.setText("Random");
        btn_rrrrrrrr1.setToolTipText("Click here for random data to be represented\n إضغط هنا لكى يتم تمثيل البيانات عشوائى");
        btn_rrrrrrrr1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btn_rrrrrrrr1StateChanged(evt);
            }
        });
        btn_rrrrrrrr1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_rrrrrrrr1MouseMoved(evt);
            }
        });
        btn_rrrrrrrr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rrrrrrrr1ActionPerformed(evt);
            }
        });

        btn_mmmmm2.setBackground(java.awt.Color.blue);
        btn_mmmmm2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_mmmmm2.setForeground(new java.awt.Color(255, 255, 255));
        btn_mmmmm2.setText("Random2");
        btn_mmmmm2.setToolTipText("Click here for random data to be represented\n إضغط هنا لكى يتم تمثيل البيانات عشوائى");
        btn_mmmmm2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btn_mmmmm2StateChanged(evt);
            }
        });
        btn_mmmmm2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_mmmmm2MouseMoved(evt);
            }
        });
        btn_mmmmm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mmmmm2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addGap(258, 258, 258)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_rrrrrrrr1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_mmmmm2))
                    .addComponent(btn_Go_prob, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton7)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_rrrrrrrr1)
                        .addComponent(btn_mmmmm2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(btn_Go_prob))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arrtime2)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(arrtime1)
                                .addGap(165, 165, 165)
                                .addComponent(arrtime))
                            .addComponent(txtNM8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNM7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNM6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNM5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNM2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNM3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNM1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNM4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(arrTime4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(arrTime3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(arrTime8)
                                        .addComponent(arrTime7)
                                        .addComponent(arrTime6)
                                        .addComponent(arrTime5)
                                        .addComponent(arrTime2)
                                        .addComponent(arrTime1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(serTime1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(serTime7)
                            .addComponent(serTime6)
                            .addComponent(serTime5)
                            .addComponent(serTime3)
                            .addComponent(serTime2)
                            .addComponent(serTime4)
                            .addComponent(serTime8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(JlblDuration)))
                        .addGap(99, 99, 99)
                        .addComponent(JlblDuration3)
                        .addGap(139, 139, 139))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOP2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOP1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOP3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOP4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOP5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOP6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOP7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOP8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(67, 67, 67))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(374, 374, 374))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlblDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrtime)
                    .addComponent(arrtime1)
                    .addComponent(arrtime2)
                    .addComponent(JlblDuration3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addComponent(arrTime4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(arrTime5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(arrTime6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(arrTime7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(arrTime8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(txtNM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(txtNM4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(txtNM5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNM6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNM7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNM8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel6)))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arrTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serTime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arrTime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serTime3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arrTime3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serTime4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serTime5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(txtOP6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(serTime6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serTime7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOP7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serTime8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOP8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
    FRM_Calc_Defult_Value f3 =new FRM_Calc_Defult_Value();
    f3.setVisible(true);
    f3.setLocationRelativeTo(null);
    f3.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    //////////////////////////////////////////////////
        Arrays.arreyTimeA[0]= Float.parseFloat(arrTime1.getText());
        Arrays.arreyTimeA[1]= Float.parseFloat(arrTime2.getText());
        Arrays.arreyTimeA[2]= Float.parseFloat(arrTime3.getText());
        Arrays.arreyTimeA[3]= Float.parseFloat(arrTime4.getText());
        Arrays.arreyTimeA[4]= Float.parseFloat(arrTime5.getText());
        Arrays.arreyTimeA[5]= Float.parseFloat(arrTime6.getText());
        Arrays.arreyTimeA[6]= Float.parseFloat(arrTime7.getText());
        Arrays.arreyTimeA[7]= Float.parseFloat(arrTime8.getText());
        ////////////////////////////////////////////////////
        Arrays.arreyServiceC[0]= Float.parseFloat(serTime1.getText());
        Arrays.arreyServiceC[1]= Float.parseFloat(serTime2.getText());
        Arrays.arreyServiceC[2]= Float.parseFloat(serTime3.getText());
        Arrays.arreyServiceC[3]= Float.parseFloat(serTime4.getText());
        Arrays.arreyServiceC[4]= Float.parseFloat(serTime5.getText());
        Arrays.arreyServiceC[5]= Float.parseFloat(serTime6.getText());
        Arrays.arreyServiceC[6]= Float.parseFloat(serTime7.getText());
        Arrays.arreyServiceC[7]= Float.parseFloat(serTime8.getText());
       /////////////////////////////
        Arrays.BeginD[0]=0;
        Arrays.Wait[0]=0;
        Arrays.WaitBegin[0]=0;
        Arrays.WaitEnd[0]=0;
        Arrays.EndE[0]=Arrays.arreyServiceC[0];
        ///////////////////////////////
        for(int i=1;i<=7;i++)
        {
            if (Arrays.arreyTimeA[i]>Arrays.EndE[i-1]||Arrays.arreyTimeA[i]==Arrays.EndE[i-1])
            {
                Arrays.BeginD[i]=Arrays.arreyTimeA[i];
                Arrays.EndE[i]=Arrays.BeginD[i]+Arrays.arreyServiceC[i];
                Arrays.Wait[i]=0;
                Arrays.WaitBegin[i]=0;
                Arrays.WaitEnd[i]=0;
            } else {
                Arrays.Wait[i]=Arrays.EndE[i-1]-Arrays.arreyTimeA[i];
                Arrays.WaitBegin[i]=Arrays.arreyTimeA[i];
                Arrays.WaitEnd[i]=Arrays.EndE[i-1];
                Arrays.BeginD[i]=Arrays.Wait[i]+Arrays.arreyTimeA[i];
                Arrays.EndE[i]=Arrays.BeginD[i]+Arrays.arreyServiceC[i];
                    }
        }
        /////////////////////////////////
        for(int i=0;i<7;i++){
        if(Arrays.BeginD[i+1]>Arrays.EndE[i])
        Arrays.IdleTime[i]=Arrays.BeginD[i+1]-Arrays.EndE[i];
        else
        Arrays.IdleTime[i]=0 ;
        } Arrays.IdleTime[7]=0 ;
        Arrays.Name[0]= txtNM1.getText();
        Arrays.Name[1]= txtNM2.getText();
        Arrays.Name[2]= txtNM3.getText();
        Arrays.Name[3]= txtNM4.getText();
        Arrays.Name[4]= txtNM5.getText();
        Arrays.Name[5]= txtNM6.getText();
        Arrays.Name[6]= txtNM7.getText();
        Arrays.Name[7]= txtNM8.getText();
        Arrays.OPType[0]= txtOP1.getText();
        Arrays.OPType[1]= txtOP2.getText();
        Arrays.OPType[2]= txtOP3.getText();
        Arrays.OPType[3]= txtOP4.getText();
        Arrays.OPType[4]= txtOP5.getText();
        Arrays.OPType[5]= txtOP6.getText();
        Arrays.OPType[6]= txtOP7.getText();
        Arrays.OPType[7]= txtOP8.getText();
}                                        
    catch (Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
                        }    
    }//GEN-LAST:event_jButton1ActionPerformed
    private void arrTime2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrTime2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrTime2ActionPerformed
    private void arrTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrTime1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrTime1ActionPerformed
    private void serTime6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serTime6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serTime6ActionPerformed
    private void arrTime7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrTime7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrTime7ActionPerformed
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try{
        btn_mmmmm2.setVisible(false);btn_rrrrrrrr1.setVisible(true);

arrTime1.setText("0");
arrTime2.setText("0");
arrTime3.setText("0");
arrTime4.setText("0");
arrTime5.setText("0");
arrTime6.setText("0");
arrTime7.setText("0");
arrTime8.setText("0");
serTime1.setText("0");
serTime2.setText("0");
serTime3.setText("0");
serTime4.setText("0");
serTime5.setText("0");
serTime6.setText("0");
serTime7.setText("0");
serTime8.setText("0");
txtNM1.setText("");
txtNM2.setText("");
txtNM3.setText("");
txtNM4.setText("");
txtNM5.setText("");
txtNM6.setText("");
txtNM7.setText("");
txtNM8.setText("");
txtOP1.setText("");
txtOP2.setText("");
txtOP3.setText("");
txtOP4.setText("");
txtOP5.setText("");
txtOP6.setText("");
txtOP7.setText("");
txtOP8.setText("");
}                                          
    catch (Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
    }
    }//GEN-LAST:event_jButton4ActionPerformed
    private void btn_randomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rand1ActionPerformed

    }//GEN-LAST:event_rand1ActionPerformed
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
try{
    
btn_mmmmm2.setVisible(false);
btn_rrrrrrrr1.setVisible(true);

arrTime1.setText(String.valueOf(Arrays.arreyTimeA[0]));
arrTime2.setText(String.valueOf(Arrays.arreyTimeA[1]));
arrTime3.setText(String.valueOf(Arrays.arreyTimeA[2]));
arrTime4.setText(String.valueOf(Arrays.arreyTimeA[3]));
arrTime5.setText(String.valueOf(Arrays.arreyTimeA[4]));
arrTime6.setText(String.valueOf(Arrays.arreyTimeA[5]));
arrTime7.setText(String.valueOf(Arrays.arreyTimeA[6]));
arrTime8.setText(String.valueOf(Arrays.arreyTimeA[7]));

serTime1.setText(String.valueOf(Arrays.arreyServiceC[0]));
serTime2.setText(String.valueOf(Arrays.arreyServiceC[1]));
serTime3.setText(String.valueOf(Arrays.arreyServiceC[2]));
serTime4.setText(String.valueOf(Arrays.arreyServiceC[3]));
serTime5.setText(String.valueOf(Arrays.arreyServiceC[4]));
serTime6.setText(String.valueOf(Arrays.arreyServiceC[5]));
serTime7.setText(String.valueOf(Arrays.arreyServiceC[6]));
serTime8.setText(String.valueOf(Arrays.arreyServiceC[7]));

txtNM1.setText(String.valueOf(Arrays.Name[0]));
txtNM2.setText(String.valueOf(Arrays.Name[1]));
txtNM3.setText(String.valueOf(Arrays.Name[2]));
txtNM4.setText(String.valueOf(Arrays.Name[3]));
txtNM5.setText(String.valueOf(Arrays.Name[4]));
txtNM6.setText(String.valueOf(Arrays.Name[5]));
txtNM7.setText(String.valueOf(Arrays.Name[6]));
txtNM8.setText(String.valueOf(Arrays.Name[7]));

txtOP1.setText(String.valueOf(Arrays.OPType[0]));
txtOP2.setText(String.valueOf(Arrays.OPType[1]));
txtOP3.setText(String.valueOf(Arrays.OPType[2]));
txtOP4.setText(String.valueOf(Arrays.OPType[3]));
txtOP5.setText(String.valueOf(Arrays.OPType[4]));
txtOP6.setText(String.valueOf(Arrays.OPType[5]));
txtOP7.setText(String.valueOf(Arrays.OPType[6]));
txtOP8.setText(String.valueOf(Arrays.OPType[7]));
}                                        
   
    catch (Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
    }
    }//GEN-LAST:event_jButton7ActionPerformed
    private void arrTime1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arrTime1KeyTyped
/*char c =evt.getKeyChar();
if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE))
    evt.consume();*/
    }//GEN-LAST:event_arrTime1KeyTyped
    private void arrTime2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arrTime2KeyTyped
       // TODO add your handling code here:
    }//GEN-LAST:event_arrTime2KeyTyped
    private void arrTime3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arrTime3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_arrTime3KeyTyped
    private void arrTime4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arrTime4KeyTyped
       // TODO add your handling code here:
    }//GEN-LAST:event_arrTime4KeyTyped
    private void arrTime5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arrTime5KeyTyped
       // TODO add your handling code here:
    }//GEN-LAST:event_arrTime5KeyTyped
    private void arrTime6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arrTime6KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_arrTime6KeyTyped
    private void arrTime7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arrTime7KeyTyped
       // TODO add your handling code here:
    }//GEN-LAST:event_arrTime7KeyTyped
    private void arrTime8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arrTime8KeyTyped
       // TODO add your handling code here:
    }//GEN-LAST:event_arrTime8KeyTyped
    private void serTime1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serTime1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_serTime1KeyTyped
    private void serTime2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serTime2KeyTyped
       // TODO add your handling code here:
    }//GEN-LAST:event_serTime2KeyTyped
    private void serTime3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serTime3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_serTime3KeyTyped
    private void serTime4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serTime4KeyTyped
       // TODO add your handling code here:
    }//GEN-LAST:event_serTime4KeyTyped
    private void serTime5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serTime5KeyTyped
     // TODO add your handling code here:
    }//GEN-LAST:event_serTime5KeyTyped
    private void serTime6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serTime6KeyTyped
       // TODO add your handling code here:
    }//GEN-LAST:event_serTime6KeyTyped
    private void serTime7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serTime7KeyTyped
       // TODO add your handling code here:
    }//GEN-LAST:event_serTime7KeyTyped
    private void serTime8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serTime8KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_serTime8KeyTyped
    private void txtNM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNM1ActionPerformed
    private void txtNM1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNM1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNM1KeyTyped
    private void txtNM7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNM7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNM7ActionPerformed
    private void txtNM7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNM7KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNM7KeyTyped
    private void txtNM6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNM6KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNM6KeyTyped
    private void txtNM5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNM5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNM5KeyTyped
    private void txtNM4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNM4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNM4KeyTyped
    private void txtNM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNM2ActionPerformed
    private void txtNM2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNM2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNM2KeyTyped
    private void txtNM8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNM8KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNM8KeyTyped
    private void txtNM3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNM3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNM3KeyTyped
    private void txtOP1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOP1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOP1KeyTyped
    private void txtOP4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOP4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOP4KeyTyped
    private void txtOP8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOP8KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOP8KeyTyped
    private void txtOP3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOP3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOP3KeyTyped
    private void txtOP2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOP2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOP2KeyTyped
    private void txtOP5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOP5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOP5KeyTyped
    private void txtOP7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOP7KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOP7KeyTyped
    private void txtOP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOP6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOP6ActionPerformed
    private void txtOP6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOP6KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOP6KeyTyped
    private void txtNM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNM3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNM3ActionPerformed
    private void rand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_randomActionPerformed

   
    }//GEN-LAST:event_btn_randomActionPerformed
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     //        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

btn_mmmmm2.setVisible(false);    }//GEN-LAST:event_formWindowOpened

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
 Color[] c = {Color.yellow,Color.BLUE,Color.LIGHT_GRAY,Color.white,
              Color.GRAY,Color.GREEN,Color.pink,
              Color.cyan,Color.ORANGE,Color.red};
int i;
i = 0+(int)(Math.random()*10);

arrTime1.setBackground(c[i]);
arrTime2.setBackground(c[i]);
arrTime3.setBackground(c[i]);
arrTime4.setBackground(c[i]);
arrTime5.setBackground(c[i]);
arrTime6.setBackground(c[i]);
arrTime7.setBackground(c[i]);
arrTime8.setBackground(c[i]);

i = 0+(int)(Math.random()*8);

serTime1.setBackground(c[i]);
serTime2.setBackground(c[i]);
serTime3.setBackground(c[i]);
serTime4.setBackground(c[i]);
serTime5.setBackground(c[i]);
serTime6.setBackground(c[i]);
serTime7.setBackground(c[i]);
serTime8.setBackground(c[i]);

i = 0+(int)(Math.random()*8);

txtNM1.setBackground(c[i]);
txtNM2.setBackground(c[i]);
txtNM3.setBackground(c[i]);
txtNM4.setBackground(c[i]);
txtNM5.setBackground(c[i]);
txtNM6.setBackground(c[i]);
txtNM7.setBackground(c[i]);
txtNM8.setBackground(c[i]);

i = 0+(int)(Math.random()*8);

txtOP1.setBackground(c[i]);
txtOP2.setBackground(c[i]);
txtOP3.setBackground(c[i]);
txtOP4.setBackground(c[i]);
txtOP5.setBackground(c[i]);
txtOP6.setBackground(c[i]);
txtOP7.setBackground(c[i]);
txtOP8.setBackground(c[i]);
      
    }//GEN-LAST:event_formMouseClicked

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseReleased

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved

    }//GEN-LAST:event_formMouseMoved

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseMoved
        // TODO add your handling code here:
    Color[] c = {Color.yellow,Color.BLUE,Color.LIGHT_GRAY,
                 Color.white,Color.GRAY,Color.GREEN,Color.pink,
                 Color.cyan,Color.ORANGE,Color.red,Color.BLACK,
                 Color.DARK_GRAY,Color.MAGENTA};
    int i;
    i = 0+(int)(Math.random()*13);
    
        btn1.setBackground(c[i]);
        btn2.setBackground(c[i]);
        btn3.setBackground(c[i]);
        btn4.setBackground(c[i]);

    }//GEN-LAST:event_btn4MouseMoved

    private void btn1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseMoved
        // TODO add your handling code here:
    Color[] c = {Color.yellow,Color.BLUE,Color.LIGHT_GRAY,Color.white,
                 Color.GRAY,Color.GREEN,Color.pink,Color.cyan,Color.ORANGE,
                 Color.red,Color.BLACK,Color.DARK_GRAY,Color.MAGENTA};
int i;
    i = 0+(int)(Math.random()*13);
    
        btn1.setBackground(c[i]);
        btn2.setBackground(c[i]);
        btn3.setBackground(c[i]);
        btn4.setBackground(c[i]);

    }//GEN-LAST:event_btn1MouseMoved

    private void btn3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseMoved
        // TODO add your handling code here:
    Color[] c = {Color.yellow,Color.BLUE,Color.LIGHT_GRAY,Color.white,
                 Color.GRAY,Color.GREEN,Color.pink,Color.cyan,Color.ORANGE,
                 Color.red,Color.BLACK,Color.DARK_GRAY,Color.MAGENTA};
int i;
    i = 0+(int)(Math.random()*13);
    
        btn1.setBackground(c[i]);
        btn2.setBackground(c[i]);
        btn3.setBackground(c[i]);
        btn4.setBackground(c[i]);
                 

    }//GEN-LAST:event_btn3MouseMoved

    private void btn2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseMoved
        // TODO add your handling code here:
    Color[] c = {Color.yellow,Color.BLUE,Color.LIGHT_GRAY,Color.white,
                 Color.GRAY,Color.GREEN,Color.pink,Color.cyan,Color.ORANGE,
                 Color.red,Color.BLACK,Color.DARK_GRAY,Color.MAGENTA};
int i;
    i = 0+(int)(Math.random()*13);
    
        btn1.setBackground(c[i]);
        btn2.setBackground(c[i]);
        btn3.setBackground(c[i]);
        btn4.setBackground(c[i]);

    }//GEN-LAST:event_btn2MouseMoved

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        jButton1.setBackground(Color.red);
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jButton1MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseWheelMoved

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton1StateChanged
        // TODO add your handling code here:  
        jButton1.setBackground(Color.BLUE);

    }//GEN-LAST:event_jButton1StateChanged

    private void jButton3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton3StateChanged
        // TODO add your handling code here:
                jButton3.setBackground(Color.BLUE);

    }//GEN-LAST:event_jButton3StateChanged

    private void jButton4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton4StateChanged
        // TODO add your handling code here:
                jButton4.setBackground(Color.BLUE);

    }//GEN-LAST:event_jButton4StateChanged

    private void jButton7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton7StateChanged
        // TODO add your handling code here:
                jButton7.setBackground(Color.BLUE);

    }//GEN-LAST:event_jButton7StateChanged

    private void btn_randomStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rand1StateChanged
        // TODO add your handling code here:
             //   btn_rrrand.setBackground(Color.BLUE);

    }//GEN-LAST:event_rand1StateChanged

    private void rand1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btn_randomStateChanged
        // TODO add your handling code here:
           //     btn_rrrand.setBackground(Color.BLUE);

    }//GEN-LAST:event_btn_randomStateChanged

    private void jButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseMoved
        // TODO add your handling code here:
        jButton3.setBackground(Color.red);
    }//GEN-LAST:event_jButton3MouseMoved

    private void jButton4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseMoved
        // TODO add your handling code here:
        jButton4.setBackground(Color.red);
    }//GEN-LAST:event_jButton4MouseMoved

    private void jButton7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseMoved
        // TODO add your handling code here:
        jButton7.setBackground(Color.red);
    }//GEN-LAST:event_jButton7MouseMoved

    private void btn_randomMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rand1MouseMoved
        // TODO add your handling code here:
       // btn_rrrand.setBackground(Color.red);
    }//GEN-LAST:event_rand1MouseMoved

    private void rand1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_randomMouseMoved
        // TODO add your handling code here:
        //btn_rrrand.setBackground(Color.red);
    }//GEN-LAST:event_btn_randomMouseMoved

    private void btn_Go_probStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btn_Go_probStateChanged
btn_Go_prob.setBackground(Color.BLUE);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Go_probStateChanged

    private void btn_Go_probMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Go_probMouseMoved
btn_Go_prob.setBackground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Go_probMouseMoved

    private void btn_Go_probActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Go_probActionPerformed
    FRM_Tables f3 =new FRM_Tables();
    f3.setVisible(true);
    f3.setLocationRelativeTo(null);
    f3.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    //////////////////////////////////////////////////
        Arrays.arreyTimeA[0]= Float.parseFloat(arrTime1.getText());
        Arrays.arreyTimeA[1]= Float.parseFloat(arrTime2.getText());
        Arrays.arreyTimeA[2]= Float.parseFloat(arrTime3.getText());
        Arrays.arreyTimeA[3]= Float.parseFloat(arrTime4.getText());
        Arrays.arreyTimeA[4]= Float.parseFloat(arrTime5.getText());
        Arrays.arreyTimeA[5]= Float.parseFloat(arrTime6.getText());
        Arrays.arreyTimeA[6]= Float.parseFloat(arrTime7.getText());
        Arrays.arreyTimeA[7]= Float.parseFloat(arrTime8.getText());
        ////////////////////////////////////////////////////
        Arrays.arreyServiceC[0]= Float.parseFloat(serTime1.getText());
        Arrays.arreyServiceC[1]= Float.parseFloat(serTime2.getText());
        Arrays.arreyServiceC[2]= Float.parseFloat(serTime3.getText());
        Arrays.arreyServiceC[3]= Float.parseFloat(serTime4.getText());
        Arrays.arreyServiceC[4]= Float.parseFloat(serTime5.getText());
        Arrays.arreyServiceC[5]= Float.parseFloat(serTime6.getText());
        Arrays.arreyServiceC[6]= Float.parseFloat(serTime7.getText());
        Arrays.arreyServiceC[7]= Float.parseFloat(serTime8.getText());
       /////////////////////////////
        


// TODO add your handling code here:
    }//GEN-LAST:event_btn_Go_probActionPerformed

    private void arrTime8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrTime8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrTime8ActionPerformed

    private void txtOP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOP2ActionPerformed

    private void btn_rrrrrrrr1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btn_rrrrrrrr1StateChanged
       
btn_rrrrrrrr1.setBackground(Color.BLUE);
        
// TODO add your handling code here:
    }//GEN-LAST:event_btn_rrrrrrrr1StateChanged

    private void btn_rrrrrrrr1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rrrrrrrr1MouseMoved
       
btn_rrrrrrrr1.setBackground(Color.red);
        
// TODO add your handling code here:
    }//GEN-LAST:event_btn_rrrrrrrr1MouseMoved

    private void btn_rrrrrrrr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rrrrrrrr1ActionPerformed

 FRM_Input_Random f4 =new FRM_Input_Random();
    f4.setVisible(true);
    f4.setLocationRelativeTo(null);
    f4.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    btn_rrrrrrrr1.setVisible(false);
    btn_mmmmm2.setVisible(true);        
// TODO add your handling code here:
    }//GEN-LAST:event_btn_rrrrrrrr1ActionPerformed

    private void btn_mmmmm2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btn_mmmmm2StateChanged
      
btn_mmmmm2.setBackground(Color.BLUE);
       
// TODO add your handling code here:
    }//GEN-LAST:event_btn_mmmmm2StateChanged

    private void btn_mmmmm2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mmmmm2MouseMoved
        
btn_mmmmm2.setBackground(Color.red);

// TODO add your handling code here:
    }//GEN-LAST:event_btn_mmmmm2MouseMoved

    private void btn_mmmmm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mmmmm2ActionPerformed
try{
   
int star=Arrays.num1;
int end = (int)((Arrays.num2));
int time=0;
{
int res = star+ (int) (Math.random()*end);
String str =String.valueOf(res+time);
arrTime1.setText(str);
time+=res;
}
{
int res = star+ (int) (Math.random()*end);
String str =String.valueOf(res+time);
arrTime2.setText(str);
time+=res;
}
{
int res = star+ (int) (Math.random()*end);
String str =String.valueOf(res+time);
arrTime3.setText(str);
time+=res;
}
{
int res = star+ (int) (Math.random()*end);
String str =String.valueOf(res+time);
arrTime4.setText(str);
time+=res;
}
{
int res = star+ (int) (Math.random()*end);
String str =String.valueOf(res+time);
arrTime5.setText(str);
time+=res;
}
{
int res = star+ (int) (Math.random()*end);
String str =String.valueOf(res+time);
arrTime6.setText(str);
time+=res;
}
{
int res = star+ (int) (Math.random()*end);
String str =String.valueOf(res+time);
arrTime7.setText(str);
time+=res;
}
{
int res = star+ (int) (Math.random()*end);
String str =String.valueOf(res+time);
arrTime8.setText(str);
time+=res;
}
star=Arrays.num3;end=Arrays.num4;
{
int res=star+ (int)(Math.random()*end);
String str =String.valueOf(res);
serTime1.setText(str);
}
{
int res=star+ (int)(Math.random()*end);
String str =String.valueOf(res);
serTime2.setText(str);
}
{
int res=star+ (int)(Math.random()*end);
String str =String.valueOf(res);
serTime3.setText(str);
}
{
int res=star+ (int)(Math.random()*end);
String str =String.valueOf(res);
serTime4.setText(str);
}
{
int res=star+ (int)(Math.random()*end);
String str =String.valueOf(res);
serTime5.setText(str);
}
{
int res=star+ (int)(Math.random()*end);
String str =String.valueOf(res);
serTime6.setText(str);
}
{
int res=star+ (int)(Math.random()*end);
String str =String.valueOf(res);
serTime7.setText(str);
}
{
int res=star+ (int)(Math.random()*end);
String str =String.valueOf(res);
serTime8.setText(str);
}
String[] name= {"Ahmed","Ali","Omer","Mohamed","Mahmoud","Saad","Fady","Abdullah","Turki","Talal","Adel","Maher","Hussam","Tariq","Samy","Salah","Khaled","Bader","Yasser","Ibrahim"};
{
int i= 0+(int)(Math.random()*20);
txtNM1.setText(name[i]);
}
{
int i= 0+(int)(Math.random()*20);
txtNM2.setText(name[i]);
}
{
int i= 0+(int)(Math.random()*20);
txtNM3.setText(name[i]);
}
{
int i= 0+(int)(Math.random()*20);
txtNM4.setText(name[i]);
}
{
int i= 0+(int)(Math.random()*20);
txtNM5.setText(name[i]);
}
{
int i= 0+(int)(Math.random()*20);
txtNM6.setText(name[i]);
}
{
int i= 0+(int)(Math.random()*20);
txtNM7.setText(name[i]);
}
{
int i= 0+(int)(Math.random()*20);
txtNM8.setText(name[i]);
}
String[] op = {"NewAccount","Inquiry","Deposit","Withdrow","Transfer"};
{
int i= 0+(int)(Math.random()*5);
txtOP1.setText(op[i]);
}
{
int i= 0+(int)(Math.random()*5);
txtOP2.setText(op[i]);
}
{
int i= 0+(int)(Math.random()*5);
txtOP3.setText(op[i]);
}
{
int i= 0+(int)(Math.random()*5);
txtOP4.setText(op[i]);
}
{
int i= 0+(int)(Math.random()*5);
txtOP5.setText(op[i]);
}
{
int i= 0+(int)(Math.random()*5);
txtOP6.setText(op[i]);
}
{
int i= 0+(int)(Math.random()*5);
txtOP7.setText(op[i]);
}
{
int i= 0+(int)(Math.random()*5);
txtOP8.setText(op[i]);
}
}                                        
    catch (Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
    }
        

// TODO add your handling code here:
    }//GEN-LAST:event_btn_mmmmm2ActionPerformed
    /**
     * @param argsthe command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Begin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Begin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Begin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Begin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Begin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlblDuration;
    private javax.swing.JLabel JlblDuration3;
    private javax.swing.JTextField arrTime1;
    private javax.swing.JTextField arrTime2;
    private javax.swing.JTextField arrTime3;
    private javax.swing.JTextField arrTime4;
    private javax.swing.JTextField arrTime5;
    private javax.swing.JTextField arrTime6;
    private javax.swing.JTextField arrTime7;
    private javax.swing.JTextField arrTime8;
    private javax.swing.JLabel arrtime;
    private javax.swing.JLabel arrtime1;
    private javax.swing.JLabel arrtime2;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn_Go_prob;
    private javax.swing.JButton btn_mmmmm2;
    private javax.swing.JButton btn_rrrrrrrr1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField serTime1;
    private javax.swing.JTextField serTime2;
    private javax.swing.JTextField serTime3;
    private javax.swing.JTextField serTime4;
    private javax.swing.JTextField serTime5;
    private javax.swing.JTextField serTime6;
    private javax.swing.JTextField serTime7;
    private javax.swing.JTextField serTime8;
    private javax.swing.JTextField txtNM1;
    private javax.swing.JTextField txtNM2;
    private javax.swing.JTextField txtNM3;
    private javax.swing.JTextField txtNM4;
    private javax.swing.JTextField txtNM5;
    private javax.swing.JTextField txtNM6;
    private javax.swing.JTextField txtNM7;
    private javax.swing.JTextField txtNM8;
    private javax.swing.JTextField txtOP1;
    private javax.swing.JTextField txtOP2;
    private javax.swing.JTextField txtOP3;
    private javax.swing.JTextField txtOP4;
    private javax.swing.JTextField txtOP5;
    private javax.swing.JTextField txtOP6;
    private javax.swing.JTextField txtOP7;
    private javax.swing.JTextField txtOP8;
    // End of variables declaration//GEN-END:variables
}
